// layouts/MainLayout.tsx
import React from 'react';
import Head from 'next/head';
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import '@/app/globals.css';

import { Comfortaa, Exo_2 } from "next/font/google";

const comfortaa = Comfortaa({
    subsets: ["latin"]
})

const exo_2 = Exo_2({
   subsets: ["latin"]
});

type MainLayoutProps = {
    children: React.ReactNode;
};

const MainLayout: React.FC<MainLayoutProps> = ({ children }) => {
    return (
        <>
            <Head>
                <title>My Next.js App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <main className={exo_2.className}>{children}</main>
            <Footer />

            <style>

            </style>
        </>
    );
};

export default MainLayout;
