import type { Metadata } from "next";
import { Inter, Unbounded, Exo_2 } from "next/font/google";
import "./globals.css";
import Header from "./../components/layouts/Header";

const inter = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <Header/>
      {children}
      </body>
    </html>
  );
}
